-- Sample data converted from staysmart_db (9).sql. Loaded once when the database file is first created.
-- Delete staysmart.db to start over with this data. One statement per line.
INSERT INTO "users"(id,username,password,fullname,email,contact_number,address,business_name,business_type,profile_image_path,role,created_at,ewallet_provider,ewallet_number,qr_image_path,about_me,emergency_contact_name,emergency_contact_phone,emergency_contact_relation,pref_language,pref_timezone) VALUES(1,'admin','123','Admin User','admin@staysmart.com','09123456789',NULL,NULL,NULL,NULL,'admin','2025-12-17 13:58:59',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'English',NULL);
INSERT INTO "users"(id,username,password,fullname,email,contact_number,address,business_name,business_type,profile_image_path,role,created_at,ewallet_provider,ewallet_number,qr_image_path,about_me,emergency_contact_name,emergency_contact_phone,emergency_contact_relation,pref_language,pref_timezone) VALUES(4,'pete','123','Pete Zedrick A. Petero','pete@gmail.com','09945822724','Blk. 2 Lot 19 Makisama Street Mandug Davao City','StaySmart','Individual Landlord','C:\Users\Admin\Pictures\Screenshots\Screenshot 2025-12-07 181323.png','owner','2025-12-17 14:55:55','GCash','09945822724',NULL,NULL,NULL,NULL,NULL,'English',NULL);
INSERT INTO "users"(id,username,password,fullname,email,contact_number,address,business_name,business_type,profile_image_path,role,created_at,ewallet_provider,ewallet_number,qr_image_path,about_me,emergency_contact_name,emergency_contact_phone,emergency_contact_relation,pref_language,pref_timezone) VALUES(5,'zed','123','Tenant Petero','zed@gmail.com','09079904440','AWdawdwa',NULL,NULL,'C:\Users\Admin\Downloads\qr_placeholder.jpg','tenant','2025-12-17 15:47:43',NULL,NULL,NULL,'Handsome Tall Guys looking for aparties','Dhenny Love Petero','09936738034','Mother dearest','English','Philippines');
INSERT INTO "users"(id,username,password,fullname,email,contact_number,address,business_name,business_type,profile_image_path,role,created_at,ewallet_provider,ewallet_number,qr_image_path,about_me,emergency_contact_name,emergency_contact_phone,emergency_contact_relation,pref_language,pref_timezone) VALUES(6,'test','123','hehey','test@gmail.com','23232',NULL,NULL,NULL,NULL,'tenant','2025-12-17 15:56:27',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'English',NULL);
INSERT INTO "users"(id,username,password,fullname,email,contact_number,address,business_name,business_type,profile_image_path,role,created_at,ewallet_provider,ewallet_number,qr_image_path,about_me,emergency_contact_name,emergency_contact_phone,emergency_contact_relation,pref_language,pref_timezone) VALUES(7,'testo','123','Test Zedrick','testo@gmail.com','0909',NULL,NULL,NULL,NULL,'owner','2025-12-17 19:33:12',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'English',NULL);
INSERT INTO "properties"(id,name,location,price,location_type,total_floors,image_path,type,floors,landlord_id,amenities,created_at) VALUES(18,'Sunshine','12312',123.0,NULL,NULL,'C:\Users\Admin\Downloads\rural1.jpg','Rural','3',NULL,NULL,'2025-12-17 12:00:00');
INSERT INTO "properties"(id,name,location,price,location_type,total_floors,image_path,type,floors,landlord_id,amenities,created_at) VALUES(19,'Urban Pool','Davao',3000.0,NULL,NULL,'C:\Users\Admin\Downloads\urban2.jpg','Urban','6',NULL,NULL,'2025-12-17 12:00:00');
INSERT INTO "properties"(id,name,location,price,location_type,total_floors,image_path,type,floors,landlord_id,amenities,created_at) VALUES(20,'Moonlight','Mandug',700.0,NULL,NULL,'C:\Users\Admin\Downloads\urban3.jpg','Urban','9',4,'Toilet & bath, Laundry area, Emergency exits, Secure main entrance / gate','2025-12-17 12:00:00');
INSERT INTO "properties"(id,name,location,price,location_type,total_floors,image_path,type,floors,landlord_id,amenities,created_at) VALUES(22,'Maui Wowie','Manila',1500.0,NULL,NULL,'C:\Users\Admin\Downloads\urban2.jpg','Urban','6',7,NULL,'2025-12-17 12:00:00');
INSERT INTO "properties"(id,name,location,price,location_type,total_floors,image_path,type,floors,landlord_id,amenities,created_at) VALUES(23,'Milo','Mandug',1000.0,NULL,NULL,'C:\Users\Admin\Downloads\urban3.jpg','Urban','7',4,'Swimming Pool, Gym, Wi-Fi, 24/7 Security, Garden, Pet Friendly','2025-12-17 12:00:00');
INSERT INTO "properties"(id,name,location,price,location_type,total_floors,image_path,type,floors,landlord_id,amenities,created_at) VALUES(25,'KapeNate','UM',2000.0,NULL,NULL,'C:\Users\Admin\Downloads\urban1.jpg','Urban','1',4,'','2025-12-17 12:00:00');
INSERT INTO "properties"(id,name,location,price,location_type,total_floors,image_path,type,floors,landlord_id,amenities,created_at) VALUES(26,'Lechon','dabaw',1212.0,NULL,NULL,'C:\Users\Admin\Downloads\rural2.jpg','Rural','4',4,'Toilet & bath, Kitchen / cooking area, Laundry area, Emergency exits, Secure main entrance / gate','2025-12-17 12:00:00');
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(63,18,1,2);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(64,18,2,1);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(65,18,3,3);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(66,19,1,2);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(67,19,2,3);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(68,19,3,4);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(69,19,4,5);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(70,19,5,1);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(71,19,6,6);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(72,20,1,8);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(73,20,2,1);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(74,20,3,7);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(75,20,4,2);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(76,20,5,6);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(77,20,6,3);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(78,20,7,5);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(79,20,8,4);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(80,20,9,2);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(83,22,1,3);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(84,22,2,4);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(85,22,3,3);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(86,22,4,4);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(87,22,5,3);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(88,22,6,4);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(89,23,1,7);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(90,23,2,6);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(91,23,3,5);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(92,23,4,4);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(93,23,5,3);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(94,23,6,2);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(95,23,7,1);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(98,25,1,3);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(99,26,1,3);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(100,26,2,4);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(101,26,3,2);
INSERT INTO "property_floors"(id,property_id,floor_number,room_count) VALUES(102,26,4,1);
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(20,18,1,'101','Occupied',4542.0,'C:\Users\Admin\Downloads\rural1.jpg','Electric fan, Study table / Desk, Electrical outlets, Extension cord (fixed)','Paid');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(21,18,1,'102','Available',1231231.0,'C:\Users\Admin\Downloads\urban3.jpg','Noneawdadw1231','Paid');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(22,18,2,'201','Occupied',450.0,'C:\Users\Admin\Downloads\urban3.jpg','Electric fan, Air-conditioned unit, Study table / Desk, Wall hooks / Hangers','Paid');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(23,18,3,'301','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(24,18,3,'302','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(25,18,3,'303','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(26,18,1,'103','Occupied',1231.0,'C:\Users\Admin\Downloads\urban2.jpg','awdad','Paid');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(27,19,1,'101','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(28,19,1,'102','Available',123123.0,'C:\Users\Admin\Downloads\urban2.jpg','None123123','Paid');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(29,19,2,'201','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(30,19,2,'202','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(31,19,2,'203','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(32,19,3,'301','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(33,19,3,'302','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(34,19,3,'303','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(35,19,3,'304','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(36,19,4,'401','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(37,19,4,'402','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(38,19,4,'403','Available',5000.0,'C:\Users\Admin\Downloads\rural1.jpg','Electric fan, Air-conditioned unit, Curtain / Window blinds, Cabinet / Closet, Study table / Desk, Wall hooks / Hangers','Paid');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(39,19,4,'404','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(40,19,4,'405','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(41,19,5,'501','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(42,19,6,'601','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(43,19,6,'602','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(44,19,6,'603','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(45,19,6,'604','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(46,19,6,'605','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(47,19,6,'606','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(48,18,3,'304','Maintenance',123123.0,'C:\Users\Admin\Downloads\qr_placeholder.jpg','Electric fan, Study table / Desk, Electrical outlets, Smoke detector','Paid');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(49,20,1,'101','Occupied',5000.0,'C:\Users\Admin\Downloads\urban1.jpg','Electric fan, Air-conditioned unit, Curtain / Window blinds, Study table / Desk, Wall hooks / Hangers, Electrical outlets, Extension cord (fixed)','Paid');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(50,20,1,'102','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(51,20,1,'103','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(52,20,1,'104','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(53,20,1,'105','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(54,20,1,'106','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(55,20,1,'107','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(56,20,1,'108','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(57,20,2,'201','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(58,20,3,'301','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(59,20,3,'302','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(60,20,3,'303','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(61,20,3,'304','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(62,20,3,'305','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(63,20,3,'306','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(64,20,3,'307','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(65,20,4,'401','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(66,20,4,'402','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(67,20,5,'501','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(68,20,5,'502','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(69,20,5,'503','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(70,20,5,'504','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(71,20,5,'505','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(72,20,5,'506','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(73,20,6,'601','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(74,20,6,'602','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(75,20,6,'603','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(76,20,7,'701','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(77,20,7,'702','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(78,20,7,'703','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(79,20,7,'704','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(80,20,7,'705','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(81,20,8,'801','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(82,20,8,'802','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(83,20,8,'803','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(84,20,8,'804','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(85,20,9,'901','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(86,20,9,'902','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(96,22,1,'101','Occupied',0.0,'C:\Users\Admin\Downloads\rural1.jpg','Electric fan, Curtain / Window blinds, Cabinet / Closet, Smoke detector','Paid');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(97,22,1,'102','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(98,22,1,'103','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(99,22,2,'201','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(100,22,2,'202','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(101,22,2,'203','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(102,22,2,'204','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(103,22,3,'301','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(104,22,3,'302','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(105,22,3,'303','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(106,22,4,'401','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(107,22,4,'402','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(108,22,4,'403','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(109,22,4,'404','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(110,22,5,'501','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(111,22,5,'502','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(112,22,5,'503','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(113,22,6,'601','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(114,22,6,'602','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(115,22,6,'603','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(116,22,6,'604','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(117,23,1,'101','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(118,23,1,'102','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(119,23,1,'103','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(120,23,1,'104','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(121,23,1,'105','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(122,23,1,'106','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(123,23,1,'107','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(124,23,2,'201','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(125,23,2,'202','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(126,23,2,'203','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(127,23,2,'204','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(128,23,2,'205','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(129,23,2,'206','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(130,23,3,'301','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(131,23,3,'302','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(132,23,3,'303','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(133,23,3,'304','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(134,23,3,'305','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(135,23,4,'401','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(136,23,4,'402','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(137,23,4,'403','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(138,23,4,'404','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(139,23,5,'501','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(140,23,5,'502','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(141,23,5,'503','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(142,23,6,'601','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(143,23,6,'602','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(144,23,7,'701','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(149,25,1,'101','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(150,25,1,'102','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(151,25,1,'103','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(152,26,1,'101','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(153,26,1,'102','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(154,26,1,'103','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(155,26,2,'201','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(156,26,2,'202','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(157,26,2,'203','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(158,26,2,'204','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(159,26,3,'301','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(160,26,3,'302','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "rooms"(id,property_id,floor_level,room_number,status,price,image_path,facilities,payment_status) VALUES(161,26,4,'401','Available',0.0,NULL,NULL,'Pending');
INSERT INTO "applications"(id,room_id,tenant_id,property_id,application_type,message,payment_method,contact_number,status,apply_date) VALUES(1,25,5,18,'Booking','Hiii, me interested','GCash / E-Wallet',NULL,'Pending','2025-12-17 22:49:04');
INSERT INTO "applications"(id,room_id,tenant_id,property_id,application_type,message,payment_method,contact_number,status,apply_date) VALUES(2,45,5,19,'Tour','Please2',NULL,'0998763512','Pending','2025-12-17 22:52:33');
INSERT INTO "saved_properties"(id,tenant_id,property_id,category,saved_at) VALUES(1,5,18,'Near Campus','2025-12-17 23:50:55');
INSERT INTO "saved_properties"(id,tenant_id,property_id,category,saved_at) VALUES(3,5,19,'Near Campus','2025-12-17 23:59:53');
